name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Security Audit
      run: npm audit
      continue-on-error: true
    
    - name: Run Tests with Coverage
      run: CI=true npm test -- --coverage
      env:
        CI: true
    
    - name: Build Production
      run: npm run build
      env:
        CI: true
    
    - name: Configure AWS Credentials
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to S3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
    
    - name: Invalidate CloudFront
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"